package com.model;

/**
 * Erjizhibiao generated by MyEclipse Persistence Tools
 */

public class Erjizhibiao implements java.io.Serializable
{

	// Fields

	private Integer erjizhibiaoDi;

	private String erjizhibiaoName;

	private String erjizhibiaoNeirong;

	private Double erjizhibiaoQuanzhong;

	private Double erjizhibiaoFenshu;

	private Integer yijizhibiaoId;

	private String del;
	
	private String yijizhibiaoName; 

	// Constructors

	/** default constructor */
	public Erjizhibiao()
	{
	}

	/** full constructor */
	public Erjizhibiao(String erjizhibiaoName, String erjizhibiaoNeirong,
			Double erjizhibiaoQuanzhong, Double erjizhibiaoFenshu,
			Integer yijizhibiaoId, String del)
	{
		this.erjizhibiaoName = erjizhibiaoName;
		this.erjizhibiaoNeirong = erjizhibiaoNeirong;
		this.erjizhibiaoQuanzhong = erjizhibiaoQuanzhong;
		this.erjizhibiaoFenshu = erjizhibiaoFenshu;
		this.yijizhibiaoId = yijizhibiaoId;
		this.del = del;
	}

	// Property accessors

	public Integer getErjizhibiaoDi()
	{
		return this.erjizhibiaoDi;
	}

	public void setErjizhibiaoDi(Integer erjizhibiaoDi)
	{
		this.erjizhibiaoDi = erjizhibiaoDi;
	}

	public String getErjizhibiaoName()
	{
		return this.erjizhibiaoName;
	}

	public void setErjizhibiaoName(String erjizhibiaoName)
	{
		this.erjizhibiaoName = erjizhibiaoName;
	}

	public String getErjizhibiaoNeirong()
	{
		return this.erjizhibiaoNeirong;
	}

	public void setErjizhibiaoNeirong(String erjizhibiaoNeirong)
	{
		this.erjizhibiaoNeirong = erjizhibiaoNeirong;
	}

	public Double getErjizhibiaoQuanzhong()
	{
		return this.erjizhibiaoQuanzhong;
	}

	public void setErjizhibiaoQuanzhong(Double erjizhibiaoQuanzhong)
	{
		this.erjizhibiaoQuanzhong = erjizhibiaoQuanzhong;
	}

	public Double getErjizhibiaoFenshu()
	{
		return this.erjizhibiaoFenshu;
	}

	public void setErjizhibiaoFenshu(Double erjizhibiaoFenshu)
	{
		this.erjizhibiaoFenshu = erjizhibiaoFenshu;
	}

	public Integer getYijizhibiaoId()
	{
		return this.yijizhibiaoId;
	}

	public void setYijizhibiaoId(Integer yijizhibiaoId)
	{
		this.yijizhibiaoId = yijizhibiaoId;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

	public String getYijizhibiaoName()
	{
		return yijizhibiaoName;
	}

	public void setYijizhibiaoName(String yijizhibiaoName)
	{
		this.yijizhibiaoName = yijizhibiaoName;
	}

}