package com.model;

/**
 * Fenshu generated by MyEclipse Persistence Tools
 */

public class Fenshu implements java.io.Serializable
{

	// Fields

	private Integer fenshuId;

	private Double fenshuFenshu;
	
	private Integer fenshuErjizhibiaoId;

	private Integer fenshuTeaId;

	private Integer fenshuStuId;

	private String shijian;
	
	private String fenshuStuName;
	
	private String fenshuErjizhibiaoName;

	// Constructors

	/** default constructor */
	public Fenshu()
	{
	}

	/** full constructor */
	public Fenshu(Double fenshuFenshu, Integer fenshuTeaId,
			Integer fenshuStuId, String shijian)
	{
		this.fenshuFenshu = fenshuFenshu;
		this.fenshuTeaId = fenshuTeaId;
		this.fenshuStuId = fenshuStuId;
		this.shijian = shijian;
	}

	// Property accessors

	public Integer getFenshuId()
	{
		return this.fenshuId;
	}

	public String getFenshuErjizhibiaoName()
	{
		return fenshuErjizhibiaoName;
	}

	public void setFenshuErjizhibiaoName(String fenshuErjizhibiaoName)
	{
		this.fenshuErjizhibiaoName = fenshuErjizhibiaoName;
	}

	public String getFenshuStuName()
	{
		return fenshuStuName;
	}

	public void setFenshuStuName(String fenshuStuName)
	{
		this.fenshuStuName = fenshuStuName;
	}

	public Integer getFenshuErjizhibiaoId()
	{
		return fenshuErjizhibiaoId;
	}

	public void setFenshuErjizhibiaoId(Integer fenshuErjizhibiaoId)
	{
		this.fenshuErjizhibiaoId = fenshuErjizhibiaoId;
	}

	public void setFenshuId(Integer fenshuId)
	{
		this.fenshuId = fenshuId;
	}

	public Double getFenshuFenshu()
	{
		return this.fenshuFenshu;
	}

	public void setFenshuFenshu(Double fenshuFenshu)
	{
		this.fenshuFenshu = fenshuFenshu;
	}

	public Integer getFenshuTeaId()
	{
		return this.fenshuTeaId;
	}

	public void setFenshuTeaId(Integer fenshuTeaId)
	{
		this.fenshuTeaId = fenshuTeaId;
	}

	public Integer getFenshuStuId()
	{
		return this.fenshuStuId;
	}

	public void setFenshuStuId(Integer fenshuStuId)
	{
		this.fenshuStuId = fenshuStuId;
	}

	public String getShijian()
	{
		return this.shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

}